spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}
jwt.secret=${JWT_SECRET}

judge0.base-url=https://ce.judge0.com
judge0.submission-path=/submissions?base64_encoded=false&wait=true

judge0.connect-timeout=5s
judge0.read-timeout=30s
